### ISSUE TITLE
NoMethodError when running `npm run publish:pact`

### ISSUE THREAD

**Issue by stlecho** [mdcruz/pact-js-example#64]
When running `npm run publish:pact` I'm getting a `NoMethodError`

As documented, I've defined the following vars
export PACT_BROKER_BASE_URL="https://slecho.pactflow.io"
export PACT_BROKER_TOKEN="_MyReadWriteToken_"

I've also tried without the quotes and with PACT_BROKER_URL and PACT_API_TOKEN, but I'm getting the same result.

```
$ npm run publish:pact

> pact@1.0.0 publish:pact
> pact-broker publish ./pacts --consumer-app-version=$GITHUB_SHA --branch=$GITHUB_BRANCH --broker-base-url=$PACT_BROKER_BASE_URL --broker-token=$PACT_BROKER_TOKEN

[15:43:24.485] WARN (66216): pact-core@14.3.8: DEPRECATION NOTICE: 
  pact standalone tools will be removed in pact-js-core 15.x.
  Please update imports to @pact-foundation/pact-cli
  https://github.com/pact-foundation/pact-js-core/issues/488
C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/hal/http_client.rb:49:in `create_request': undefined method `request_uri' for an instance of URI::Generic (NoMethodError)

          request = Net::HTTP.const_get(http_method).new(uri.request_uri)
                                                            ^^^^^^^^^^^^
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/hal/http_client.rb:25:in `get'
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/hal/link.rb:41:in `get'
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/hal/link.rb:45:in `get!'
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/hal_client_methods.rb:24:in `index_resource'
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/publish_pacts.rb:33:in `call'
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/publish_pacts.rb:16:in `call'
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/cli/pact_commands.rb:74:in `publish_pacts'
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/cli/pact_commands.rb:33:in `publish'
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'      
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'        
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'      
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/vendor/ruby/3.3.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/cli/custom_thor.rb:34:in `start'
        from C:/projects/GitHub/pact-js-example/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.4.6/pact/lib/app/pact-broker.rb:34:in `<main>'
```

**Comment by rusty22** [comment]
Got this error as well. To fix this I had to update the `package.json` `publish:pact` command with this:
```
cross-env npx pact-broker publish ./pacts --consumer-app-version=1.0.0 --tag=main --broker-base-url=$PACT_BROKER_BASE_URL --broker-token=$PACT_BROKER_TOKEN
```

Result:
```
$ npm run publish:pact

> pact@1.0.0 publish:pact
> cross-env npx pact-broker publish ./pacts --consumer-app-version=1.0.0 --tag=main --broker-base-url=$PACT_BROKER_BASE_URL --broker-token=$PACT_BROKER_TOKEN

Created WebConsumer version 1.0.0 with tags main
  Next steps:
    Configure the version branch to be the value of your repository branch.
Pact successfully published for WebConsumer version 1.0.0 and provider MoviesAPI.
  View the published pact at https://xyz.pactflow.io/pacts/provider/MoviesAPI/consumer/WebConsumer/version/1.0.0
  Events detected: contract_published, contract_content_changed (first time any pact published for this consumer with consumer version tagged main)
  Next steps:
    * Add Pact verification tests to the MoviesAPI build. See https://docs.pact.io/go/provider_verification 
    * Configure separate MoviesAPI pact verification build and webhook to trigger it when the pact content changes. See https://docs.pact.io/go/webhooks
```
